// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faflzgtrtjfxanusaltc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhZmx6Z3RydGpmeGFudXNhbHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDY2ODksImV4cCI6MjA1OTUyMjY4OX0.0n1xw1XzfjdVEa6XFi9cQDfAJe1_jgM66xr05hOsi1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);